# Generated by Django 5.2.5 on 2025-09-21 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='staffid',
        ),
    ]
