# Generated by Django 5.2.5 on 2025-09-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_staffid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('marker', 'Marker')], default='marker', max_length=10),
        ),
    ]
