# Generated by Django 5.2.5 on 2025-09-09 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=64)),
                ('staffid', models.CharField(max_length=64)),
                ('profile_picture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=64)),
                ('staffid', models.CharField(max_length=64)),
                ('profile_picture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField()),
                ('rubric', models.FileField(upload_to='')),
                ('assignment_file', models.FileField(upload_to='')),
                ('mark_criteria', models.JSONField()),
                ('due_date', models.DateTimeField()),
                ('administrator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.administrator')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('submission_file', models.FileField(upload_to='')),
                ('comment', models.TextField()),
                ('admin_marks', models.JSONField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.JSONField()),
                ('is_finalized', models.BooleanField()),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.assignment')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.submission')),
            ],
        ),
    ]
