# Generated by Django 5.2.5 on 2025-09-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='profile_picture',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='staffid',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='profile_picture',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='marker',
            name='staffid',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
