# Generated by Django 5.2.5 on 2025-09-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='name',
            field=models.CharField(default='Assignment', max_length=64),
            preserve_default=False,
        ),
    ]
